/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu.Cliente;

import crud.Classes.ContenedorDatos;
import crud.Classes.Conexion;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;

/**
 *
 * @author lucas
 */
public class ClienteView extends javax.swing.JFrame {

    private DefaultTableModel dtm;

    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
        dtm = (DefaultTableModel) autosTable.getModel();

        cargarAutos(ContenedorDatos.getInstance().getIdUser());
    }

    public void cargarAutos(int cliente_id) {
        dtm.setRowCount(0);
        try (Connection conn = Conexion.getConexion()) {
            String autosQuery = "SELECT * FROM vehiculos WHERE propietario_id = ? AND estado = 'disp'";
            PreparedStatement pst = conn.prepareStatement(autosQuery);
            pst.setInt(1, ContenedorDatos.getInstance().getIdUser());

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                dtm.addRow(new Object[]{
                    rs.getString("patente"),
                    rs.getString("marca"),
                    rs.getString("modelo"),
                    rs.getInt("anio")
                });
            }
            System.out.println("Autos actualizados");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los autos del cliente: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        autosTable = new javax.swing.JTable();
        AgregarAuto = new javax.swing.JButton();
        EliminarAuto = new javax.swing.JButton();
        turnoBtn = new javax.swing.JButton();
        refreshAutos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        autosTable.setBackground(new java.awt.Color(153, 153, 153));
        autosTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        autosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patente", "Marca", "Modelo", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(autosTable);
        if (autosTable.getColumnModel().getColumnCount() > 0) {
            autosTable.getColumnModel().getColumn(0).setResizable(false);
            autosTable.getColumnModel().getColumn(1).setResizable(false);
            autosTable.getColumnModel().getColumn(2).setResizable(false);
            autosTable.getColumnModel().getColumn(3).setResizable(false);
        }

        AgregarAuto.setBackground(new java.awt.Color(153, 153, 153));
        AgregarAuto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        AgregarAuto.setForeground(new java.awt.Color(51, 51, 51));
        AgregarAuto.setText("Agregar");
        AgregarAuto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AgregarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAutoActionPerformed(evt);
            }
        });

        EliminarAuto.setBackground(new java.awt.Color(153, 153, 153));
        EliminarAuto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        EliminarAuto.setForeground(new java.awt.Color(51, 51, 51));
        EliminarAuto.setText("Eliminar");
        EliminarAuto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EliminarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAutoActionPerformed(evt);
            }
        });

        turnoBtn.setBackground(new java.awt.Color(153, 153, 153));
        turnoBtn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        turnoBtn.setForeground(new java.awt.Color(51, 51, 51));
        turnoBtn.setText("Sacar Turno");
        turnoBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        turnoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnoBtnActionPerformed(evt);
            }
        });

        refreshAutos.setBackground(new java.awt.Color(153, 153, 153));
        refreshAutos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        refreshAutos.setForeground(new java.awt.Color(51, 51, 51));
        refreshAutos.setText("Actualizar Lista");
        refreshAutos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refreshAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(turnoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EliminarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgregarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(refreshAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(refreshAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AgregarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(turnoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAutoActionPerformed
        CargarAutoView cargarAuto = new CargarAutoView(this);
        cargarAuto.setVisible(true);
        cargarAuto.setLocationRelativeTo(null);
    }//GEN-LAST:event_AgregarAutoActionPerformed

    private void EliminarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAutoActionPerformed
        // TODO add your handling code here:
        String patenteAuto = JOptionPane.showInputDialog(this, "Ingrese la Patente del Auto a Eliminar");
        if (patenteAuto != null && !patenteAuto.isEmpty()) {
            try (Connection conn = Conexion.getConexion()) {
                String deleteAutoQuery = "UPDATE vehiculos SET estado = 'borrado' WHERE patente = ?";
                PreparedStatement pst = conn.prepareStatement(deleteAutoQuery);
                pst.setString(1, patenteAuto);
                int rs = pst.executeUpdate();
                if (rs > 0) {
                    JOptionPane.showMessageDialog(this, "Auto Eliminado Exitosamente");
                    cargarAutos(ContenedorDatos.getInstance().getIdUser());
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el auto.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese una Patente Válida.");
            }
        }
    }//GEN-LAST:event_EliminarAutoActionPerformed

    private void refreshAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAutosActionPerformed
        // TODO add your handling code here:
        cargarAutos(ContenedorDatos.getInstance().getIdUser());
    }//GEN-LAST:event_refreshAutosActionPerformed

    private void turnoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnoBtnActionPerformed
        // TODO add your handling code here:
        SacarTurnoView sacarTurno = new SacarTurnoView();
        sacarTurno.setVisible(true);
        sacarTurno.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_turnoBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAuto;
    private javax.swing.JButton EliminarAuto;
    private javax.swing.JTable autosTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshAutos;
    private javax.swing.JButton turnoBtn;
    // End of variables declaration//GEN-END:variables
}
