/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu.Inspector;

import crud.Classes.ContenedorDatos;
import crud.Classes.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class ConfirmarTurnoView extends javax.swing.JFrame {

    private DefaultTableModel dtm;

    /**
     * Creates new form ConfirmarTurnoView2
     */
    public ConfirmarTurnoView(int nro) {
        initComponents();
        dtm = (DefaultTableModel) turnoDataTable.getModel();

        try (Connection conn = Conexion.getConexion()) {
            if (conn != null) {
                String turnoQuery = "SELECT vehiculos.marca, vehiculos.modelo, vehiculos.anio, usuarios.nombre AS propietario, clientes.dni, clientes.telefono FROM turnos INNER JOIN vehiculos ON turnos.vehiculo_id = vehiculos.id INNER JOIN clientes ON vehiculos.propietario_id = clientes.usuario_id INNER JOIN usuarios ON clientes.usuario_id = usuarios.id INNER JOIN talleres ON turnos.taller_id = talleres.id WHERE turnos.id = ?;";
                PreparedStatement pst = conn.prepareStatement(turnoQuery);
                pst.setInt(1, nro);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    Object[] datos = {
                        rs.getString("marca"),
                        rs.getString("modelo"),
                        rs.getInt("anio"),
                        rs.getString("propietario"),
                        rs.getString("dni"),
                        rs.getString("telefono")
                    };
                    dtm.addRow(datos);
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró el turno.");
                    dispose();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        turnoDataTable = new javax.swing.JTable();
        turnoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 0));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        turnoDataTable.setBackground(new java.awt.Color(153, 153, 153));
        turnoDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Año", "Nombre Prop", "DNI", "Telf"
            }
        ));
        jScrollPane1.setViewportView(turnoDataTable);

        turnoBtn.setBackground(new java.awt.Color(153, 153, 153));
        turnoBtn.setText("CONFIRMAR");
        turnoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnoBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos del Turno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(turnoBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(turnoBtn)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void turnoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnoBtnActionPerformed
        try (Connection conn = Conexion.getConexion()) {
            if (conn != null) {
                int idInspector = ContenedorDatos.getInstance().getIdUser();
                int idTurno = ContenedorDatos.getInstance().getIdTurno();
                String creaInspQuery = "INSERT INTO inspecciones (`inspector_id`, `turno_id`, `estado`) VALUES (?, ?, ?)";

                PreparedStatement pst = conn.prepareStatement(creaInspQuery, Statement.RETURN_GENERATED_KEYS);
                pst.setInt(1, idInspector);
                pst.setInt(2, idTurno);
                pst.setString(3, "En Proceso");

                int rowsAffected = pst.executeUpdate();

                if (rowsAffected > 0) {
                    ResultSet generatedKeys = pst.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        int idGenerado = generatedKeys.getInt(1);
                        ContenedorDatos.getInstance().setIdInspeccion(idGenerado);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo crear la inspección.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

        Inspeccion ins = new Inspeccion();
        ins.setVisible(true);
        ins.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_turnoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton turnoBtn;
    private javax.swing.JTable turnoDataTable;
    // End of variables declaration//GEN-END:variables
}
